platform :ios, '11'
target 'FFitWorld' do
    pod ‘AFNetworking’, '~> 4.0'
    pod 'SDWebImage', git:'https://gitee.com/lf01/SDWebImage.git'
    pod 'TXIMSDK_iOS', '~> 4.9.1'
    pod 'ISVImageScrollView', '~> 0.1.2'
    pod 'TXIMSDK_TUIKit_iOS'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'HMSegmentedControl'
    pod 'JYCarousel'
end
